sudo: required
services:
  - docker

before_install:
  - docker build -t dkyw/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev

script:
  - docker run -e CI=true dkyw/react-test npm test -- -- coverage

after_success:
  - docker build -t dkyw00/multi-client ./client
  - docker build -t dkyw00/multi-nginx ./nginx
  - docker build -t dkyw00/multi-server ./server
  - docker build -t dkyw00/multi-worker ./worker

  # log in to the docker CLI
  - echo "$DOCKER_PASASWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push dkyw00/multi-client
  - docker push dkyw00/multi-nginx
  - docker push dkyw00/multi-server
  - docker push dkyw00/multi-worker
